pipeline {
    agent any

    tools {
        maven 'MavenDefault'
        jdk 'JDKDefault'
    }

    environment {
        SPRING_PROFILES_ACTIVE = 'dev'
    }

     stages {
            stage('Build') {
                steps {
                    dir('book-network') {
                        bat 'mvn clean package -DskipTests'
                    }
                }
            }

            stage('Test') {
                steps {
                    dir('book-network') {
                        bat 'mvn test'
                    }
                }
            }

            stage('Archive JAR') {
                steps {
                    dir('book-network') {
                        archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                    }
                }
            }
     }
}
