services:
  postgres:
    container_name: postgres-sql-bn
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DATA: /var/lib/postgresql/data
      POSTGRES_DB: book_network_db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-network
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - spring-network
  bsn-api:
    container_name: bsn-api
    image: bsn-api:1.0.0
    ports:
      - 8088:8088
    networks:
      - spring-network
    depends_on:
      - postgres
      - elasticsearch


  keycloak:
    container_name: keycloak-bsn
    image: quay.io/keycloak/keycloak:24.0.2
    volumes:
      - ./keycloak/realm/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - spring-network
    command:
      - "start-dev"
      - "--import-realm"

  elasticsearch:
    container_name: elasticsearch-bn
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
    networks:
      - spring-network
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5


  bsn-api:
    container_name: bsn-api
    image: bsn/bsn:1.0.8
    ports:
      - 8088:8088
    networks:
      - spring-network
    depends_on:
      - postgres
      - elasticsearch
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-sql-bn:5432/book_network_db
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATA_ELASTICSEARCH_URIS: http://elasticsearch-bn:9200
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak-bsn:8080/realms/book-social-network

  bsn-ui:
    container_name: bsn-ui
    image: bsn/bsn-ui:1.0.0
    ports:
      - 8080:80
    networks:
      - spring-network
    depends_on:
      - bsn-api


networks:
  spring-network:
    driver: bridge

volumes:
  postgres:
    driver: local
  keycloak:
    driver: local
  elastic_data:
    driver: local