spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/book_network_db
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  data:
    elasticsearch:
      uris: http://elasticsearch:9200
      connection-timeout: 5s
      socket-timeout: 5s
  
  retry:
    enable: true
    max-attempts: 10
    initial-interval: 2000
    multiplier: 2.0
    
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: beatrice
    password: beatrice
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimout: 5000
        timeout: 3000
        writetimeout: 5000
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/book-social-network"
  web:
    resources:
      static-locations: file:./uploads/
application:
  file:
    upload:
      photos-output-path: ./uploads
server:
  port: 8088

